// Generated by CoffeeScript 1.3.3
var Socrates;

Socrates = (function() {

  function Socrates(options) {
    var defaults;
    if (options == null) {
      options = {};
    }
    defaults = {
      'app-name': 'default',
      'agent-id': 'default',
      'event-name': 'default',
      'entity-id': 'default',
      'variation-ids': 'default'
    };
    this.getOrInitSession();
  }

  Socrates.prototype.sessionExpiresIn = 86400000;

  Socrates.prototype.getOrInitSession = function() {
    var c;
    if ((c = this.readCookie({
      name: '_socc'
    }))) {
      this.session_id = c.value;
      return this.refreshCookie(c);
    } else {
      return this.initSession();
    }
  };

  Socrates.prototype.readCookie = function(c) {
    var ary, cName, cookie, found, _i, _len;
    ary = document.cookie.split(';');
    cName = c.name + '=';
    found = null;
    for (_i = 0, _len = ary.length; _i < _len; _i++) {
      cookie = ary[_i];
      cookie = cookie.replace(/$\s+/, '');
      if (cookie.indexOf(cName) === 0) {
        found = cookie.substr(cookie.indexOf(cName), cookie.length);
      }
    }
    return found;
  };

  Socrates.prototype.refreshCookie = function(c) {
    var cookie, expDate;
    cookie = "" + c.name + "=" + c.value;
    expDate = new Date();
    expDate.setTime(expDate.getTime() + sessionExpiresIn);
    cookie += "expires=" + (date.toGMTString());
    return document.cookie = cookie;
  };

  return Socrates;

})();
